PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id":5,
  "title": "What's new with NestJS With TypeScript",
  "postType": "post",
  "status": "draft",
  "content": "test content",
  "metaOptions" : {
      "metaValue": "{\"sidebarEnabled\": true, \"footerActive\":true}"
    },
  "tags": [1,2]
}