PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 17,
  "title": "What's new with NestJS",
  "postType": "post",
  "status": "published",
  "content": "test content",
  "publishOn": "2024-03-16T07:46:32+0000",
  //"tags": ["nestjs", "typescript"],
  "metaOptions" : {
    "metaValue": "{ \"sidebarEnabled\": true, \"footerActive\": true }"
    },
  "tags": [4,7]
}